### ISSUE TITLE
Npm package not update

### ISSUE THREAD

**Issue by maarekj** [jaredly/let-anything#1]
Hi,
the version of let-anything on npm is not update with the last source.
As a result we get an error on install this ppx:

```
Package not found: resolving package rex-json in /
```

**Comment by stouf** [comment]
I got bitten by the same problem today. I forked this repository and simply added `rex-json` to the list of the dependencies in the `package.json` file. I then tried to install my fork in a different project and it worked.

@jaredly I must admit not being super familiar with this codebase yet, but does it sound like what I wrote above would solve the issue the right way?

**Comment by maarekj** [comment]
It seems to me that the problem is already solved on the master branch.
But, the version present on npm repositories is not the same as the version of the master branch.

**Comment by jaredly** [comment]
just published a fix to npm

**Comment by stouf** [comment]
I confirmed it now works for me!
Thanks for publishing the fix to NPM :)
