### ISSUE TITLE
Doc: installation procedure

### ISSUE THREAD

**Issue by stouf** [jaredly/let-anything#2]
I think more information about the installation procedure of this package in the `README.md` would be welcome. First of all, let me confirm the following steps are a correct installation procedure:

1. Install the NPM package `let-anything` through your favorite NPM package manager (NPM itself or Yarn for example)
2. The previous step should compile a binary whose location is `node_modules/let-anything/lib/bs/native/let_anything.native`. Add this path to the `ppx-flags` defined in your `bsconfig.json` file (see https://bucklescript.github.io/bucklescript/docson/#build-schema.json)
3. Have fun :)

If the above is correct, what do you think about adding it to the `README.md`?
Now, I think most of it is actually pretty obvious and easy to guess. Maybe only adding a note about the path of the binary would be enough? What do you think?

**Comment by jihchi** [comment]
Hi @stouf ,

I tried that binary location should be `./node_modules/let-anything/lib/bs/native/let_anything.native` instead of `node_modules/let-anything/lib/bs/native/let_anything.native`.

(OS: Ubuntu 16.04)

**Comment by stouf** [comment]
Hi @jihchi 

Yes, I confirm :+1: When you want to use a path on your file system there, you need to prepend `./` to it. Otherwise, Bucklescript will consider what you give it a package; for example, with `reason/reactjs_jsx_ppx_3.native`, Bucklescript will look for the `reactjs_jsx_ppx_3.native` file in the `reason` package, whose location will probably be `node_modules/reason/reactjs_jsx_ppx_3.`.

**Comment by jihchi** [comment]
@stouf 

Great! `let-anything/lib/bs/native/let_anything.native` is better, it works as well! 
Thank you for detail explaining.
