### ISSUE TITLE
Uninterpreted extension 'Async'

### ISSUE THREAD

**Issue by svsool** [jaredly/let-anything#6]
Hello and thank you for this extension. I get an error in console `Uninterpreted extension 'Async'` on running `npm run build` with such configuration:

```
"devDependencies": {
    "bs-platform": "4.0.18",
    "let-anything": "^1.0.3"
  }
```

```
The OCaml toplevel, version 4.02.3
```

```
MacOS Mojave
Version 10.14.4
```

Not sure if it's a bug or somehow related to ocaml version or bs-platform version.

I also tried it with `"bs-platform": "5.0.3"`.

Repro can be found in https://github.com/svsool/lets-test

Please run:

```
npm i
npm run build
```

**Comment by svsool** [comment]
@jaredly please take a look when you will have time

**Comment by Coobaha** [comment]
TWIMC it only matches lets inside function body
this works:
```
// A.re
let test = () => {
 let%Async test = Js.Promise.resolve();
}
```
but this doesn't
```
// A.re
let%Async test = Js.Promise.resolve();
```
